import { Item } from "@prisma/client";
import exp from "constants";

const items: Item[] = [
  {
    id: 1,
    name: "Wireless Mouse",
    quantity: 100,
    amountSold: 50,
    price: 29.99,
    description: "A high-precision wireless mouse with ergonomic design.",
    category: "Electronics",
    manufacturer: "TechBrand",
    sku: "WM12345",
    imageUrl: "https://example.com/images/wireless-mouse.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.5,
  },
  {
    id: 2,
    name: "Gaming Keyboard",
    quantity: 200,
    amountSold: 75,
    price: 79.99,
    description: "Mechanical gaming keyboard with RGB lighting.",
    category: "Electronics",
    manufacturer: "GameTech",
    sku: "GK67890",
    imageUrl: "https://example.com/images/gaming-keyboard.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 36,
    ratings: 4.7,
  },
  {
    id: 3,
    name: "Bluetooth Headphones",
    quantity: 150,
    amountSold: 60,
    price: 49.99,
    description:
      "Comfortable over-ear Bluetooth headphones with noise cancellation.",
    category: "Electronics",
    manufacturer: "SoundPro",
    sku: "BH11223",
    imageUrl: "https://example.com/images/bluetooth-headphones.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 12,
    ratings: 4.3,
  },
  {
    id: 4,
    name: "Smartwatch",
    quantity: 80,
    amountSold: 30,
    price: 199.99,
    description:
      "Feature-packed smartwatch with fitness tracking and notifications.",
    category: "Wearables",
    manufacturer: "WristTech",
    sku: "SW33445",
    imageUrl: "https://example.com/images/smartwatch.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 18,
    ratings: 4.6,
  },
  {
    id: 5,
    name: "4K Monitor",
    quantity: 50,
    amountSold: 20,
    price: 349.99,
    description: "Ultra HD 4K monitor with stunning picture quality.",
    category: "Electronics",
    manufacturer: "DisplayPro",
    sku: "KM55667",
    imageUrl: "https://example.com/images/4k-monitor.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.8,
  },
  {
    id: 6,
    name: "Portable Charger",
    quantity: 300,
    amountSold: 150,
    price: 19.99,
    description: "Compact portable charger with 10000mAh capacity.",
    category: "Accessories",
    manufacturer: "PowerTech",
    sku: "PC12345",
    imageUrl: "https://example.com/images/portable-charger.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 12,
    ratings: 4.2,
  },
  {
    id: 7,
    name: "Smart Speaker",
    quantity: 120,
    amountSold: 60,
    price: 129.99,
    description: "Voice-controlled smart speaker with high-fidelity sound.",
    category: "Electronics",
    manufacturer: "SoundHome",
    sku: "SS67890",
    imageUrl: "https://example.com/images/smart-speaker.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.4,
  },
  {
    id: 8,
    name: "Fitness Tracker",
    quantity: 150,
    amountSold: 70,
    price: 99.99,
    description: "Fitness tracker with heart rate monitor and GPS.",
    category: "Wearables",
    manufacturer: "FitTech",
    sku: "FT11223",
    imageUrl: "https://example.com/images/fitness-tracker.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 18,
    ratings: 4.6,
  },
  {
    id: 9,
    name: "Digital Camera",
    quantity: 75,
    amountSold: 30,
    price: 599.99,
    description: "Digital camera with 24MP sensor and 4K video recording.",
    category: "Electronics",
    manufacturer: "PhotoPro",
    sku: "DC33445",
    imageUrl: "https://example.com/images/digital-camera.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.7,
  },
  {
    id: 10,
    name: "Wireless Earbuds",
    quantity: 200,
    amountSold: 90,
    price: 39.99,
    description: "True wireless earbuds with Bluetooth 5.0 and charging case.",
    category: "Electronics",
    manufacturer: "SoundPro",
    sku: "WE55667",
    imageUrl: "https://example.com/images/wireless-earbuds.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 12,
    ratings: 4.3,
  },
  {
    id: 11,
    name: "Laptop Stand",
    quantity: 180,
    amountSold: 80,
    price: 24.99,
    description: "Adjustable laptop stand for better ergonomics.",
    category: "Accessories",
    manufacturer: "DeskComfort",
    sku: "LS12345",
    imageUrl: "https://example.com/images/laptop-stand.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 12,
    ratings: 4.5,
  },
  {
    id: 12,
    name: "USB-C Hub",
    quantity: 250,
    amountSold: 100,
    price: 49.99,
    description: "Multi-port USB-C hub with HDMI, USB 3.0, and Ethernet.",
    category: "Accessories",
    manufacturer: "TechHub",
    sku: "UH67890",
    imageUrl: "https://example.com/images/usb-c-hub.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.4,
  },
  {
    id: 13,
    name: "Action Camera",
    quantity: 60,
    amountSold: 20,
    price: 299.99,
    description: "Waterproof action camera with 4K video and Wi-Fi.",
    category: "Electronics",
    manufacturer: "AdventureCam",
    sku: "AC11223",
    imageUrl: "https://example.com/images/action-camera.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.5,
  },
  {
    id: 14,
    name: "VR Headset",
    quantity: 90,
    amountSold: 40,
    price: 399.99,
    description: "Immersive VR headset with 110-degree field of view.",
    category: "Electronics",
    manufacturer: "VirtualTech",
    sku: "VR33445",
    imageUrl: "https://example.com/images/vr-headset.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 12,
    ratings: 4.7,
  },
  {
    id: 15,
    name: "Wireless Charger",
    quantity: 200,
    amountSold: 100,
    price: 29.99,
    description: "Fast wireless charger with 10W output.",
    category: "Accessories",
    manufacturer: "ChargePro",
    sku: "WC55667",
    imageUrl: "https://example.com/images/wireless-charger.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 12,
    ratings: 4.4,
  },
  {
    id: 16,
    name: "Noise Cancelling Headphones",
    quantity: 100,
    amountSold: 40,
    price: 199.99,
    description: "Over-ear headphones with active noise cancelling technology.",
    category: "Electronics",
    manufacturer: "SoundPro",
    sku: "NC12345",
    imageUrl: "https://example.com/images/noise-cancelling-headphones.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.6,
  },
  {
    id: 17,
    name: "Electric Toothbrush",
    quantity: 150,
    amountSold: 70,
    price: 59.99,
    description:
      "Rechargeable electric toothbrush with multiple brushing modes.",
    category: "Personal Care",
    manufacturer: "SmileTech",
    sku: "ET67890",
    imageUrl: "https://example.com/images/electric-toothbrush.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 24,
    ratings: 4.7,
  },
  {
    id: 18,
    name: "E-Reader",
    quantity: 100,
    amountSold: 50,
    price: 129.99,
    description:
      "E-Reader with high-resolution display and adjustable backlight.",
    category: "Electronics",
    manufacturer: "ReadEase",
    sku: "ER11223",
    imageUrl: "https://example.com/images/e-reader.jpg",
    dateAdded: new Date(),
    warrantyPeriod: 12,
    ratings: 4.5,
  },
];
export default items;
